package com.neunn.ruma.entity;

import java.util.Date;

import com.neunn.ruma.common.persistence.DataEntity;

public class ModuleEntity extends DataEntity<RoleEntity> {
    /**
     * FIXME 删除本行替换为字段描述
     * 
     * @author Frank
     * @date 2016年3月10日
     */
    private static final long serialVersionUID = -1806904447786842441L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * module_info.id
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * module_info.name
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * module_info.description
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * module_info.parent_id
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * module_info.name
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    private String parentName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * module_info.request_url
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    private String requestUrl;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * module_info.request_method
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    private String requestMethod;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * module_info.creat_user
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    private String creatUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * module_info.creat_time
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * module_info.modify_user
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * module_info.modify_time
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    private Date modifyTime;

    /**
     * 操作按钮的连接字符串，"增加，删除，修改"
     */
    private String operations;
    
    /**
     * 1按钮 0菜单
     */
    private int isleap;
    
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column module_info.id
     *
     * @return the value of module_info.id
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column module_info.id
     *
     * @param id the value for module_info.id
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column module_info.name
     *
     * @return the value of module_info.name
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column module_info.name
     *
     * @param name the value for module_info.name
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column module_info.description
     *
     * @return the value of module_info.description
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column module_info.description
     *
     * @param description the value for module_info.description
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column module_info.parent_id
     *
     * @return the value of module_info.parent_id
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column module_info.parent_id
     *
     * @param parentId the value for module_info.parent_id
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column module_info.name
     *
     * @return the value of module_info.name
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column module_info.name
     *
     * @param parentId the value for module_info.name
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column module_info.request_url
     *
     * @return the value of module_info.request_url
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public String getRequestUrl() {
        return requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column module_info.request_url
     *
     * @param parentId the value for module_info.request_url
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column module_info.request_method
     *
     * @return the value of module_info.request_url
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public String getRequestMethod() {
        return requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column module_info.request_method
     *
     * @param parentId the value for module_info.request_method
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public void setRequestMethod(String requestMethod) {
        this.requestMethod = requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column module_info.creat_user
     *
     * @return the value of module_info.creat_user
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public String getCreatUser() {
        return creatUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column module_info.creat_user
     *
     * @param creatUser the value for module_info.creat_user
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public void setCreatUser(String creatUser) {
        this.creatUser = creatUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column module_info.creat_time
     *
     * @return the value of module_info.creat_time
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column module_info.creat_time
     *
     * @param creatTime the value for module_info.creat_time
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column module_info.modify_user
     *
     * @return the value of module_info.modify_user
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column module_info.modify_user
     *
     * @param modifyUser the value for module_info.modify_user
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column module_info.modify_time
     *
     * @return the value of module_info.modify_time
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column module_info.modify_time
     *
     * @param modifyTime the value for module_info.modify_time
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
    
    /**
     * @return the isleap
     */
    public int getIsleap() {
        return isleap;
    }

    /**
     * @param isleap the isleap to set
     */
    public void setIsleap(int isleap) {
        this.isleap = isleap;
    }

    public String getOperations() {
        return operations;
    }

    public void setOperations(String operations) {
        this.operations = operations;
    }

    public boolean equals(Object obj) {
        if (obj instanceof ModuleEntity) {
            if (((ModuleEntity) obj).getId().equals(this.id)) {
                return true;
            }
        }
        return false;
    }
}
