package com.neunn.ruma.entity;

import java.util.Date;

public class RoleRightsEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_rights_info.id
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_rights_info.role_id
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_rights_info.module_id
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    private String moduleId;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_info.name
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_rights_info.creat_user
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    private String creatUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_rights_info.creat_time
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_rights_info.modify_user
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_rights_info.modify_time
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_rights_info.id
     *
     * @return the value of role_rights_info.id
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_rights_info.id
     *
     * @param id the value for role_rights_info.id
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_rights_info.role_id
     *
     * @return the value of role_rights_info.role_id
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_rights_info.role_id
     *
     * @param roleId the value for role_rights_info.role_id
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_rights_info.module_id
     *
     * @return the value of role_rights_info.module_id
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_rights_info.module_id
     *
     * @param moduleId the value for role_rights_info.module_id
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_info.name
     *
     * @return the value of module_info.name
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_info.name
     *
     * @param moduleId the value for module_info.name
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_rights_info.creat_user
     *
     * @return the value of role_rights_info.creat_user
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    public String getCreatUser() {
        return creatUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_rights_info.creat_user
     *
     * @param creatUser the value for role_rights_info.creat_user
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    public void setCreatUser(String creatUser) {
        this.creatUser = creatUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_rights_info.creat_time
     *
     * @return the value of role_rights_info.creat_time
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_rights_info.creat_time
     *
     * @param creatTime the value for role_rights_info.creat_time
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_rights_info.modify_user
     *
     * @return the value of role_rights_info.modify_user
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_rights_info.modify_user
     *
     * @param modifyUser the value for role_rights_info.modify_user
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_rights_info.modify_time
     *
     * @return the value of role_rights_info.modify_time
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_rights_info.modify_time
     *
     * @param modifyTime the value for role_rights_info.modify_time
     *
     * @mbggenerated Wed May 27 11:14:57 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}