/**
 * @项目名称: ruma-web
 * @文件名称: RoleEntity.java
 * @Date: 2016年2月24日
 * @Copyright: 2016-2016 www.neunn.com All rights reserved. 注意：本内容仅限于东网科技有限公司内部传阅，禁止外泄以及用于其他的商业目的
 */
package com.neunn.ruma.entity;

import java.util.Date;
import java.util.List;

import com.neunn.ruma.common.persistence.DataEntity;

/**
 * FIXME 此处填写类的描述信息
 * 
 * @author Frank
 * @date 2016年2月24日
 * @since 1.0
 */
public class RoleEntity extends DataEntity<RoleEntity> {
    /**
     * FIXME 删除本行替换为字段描述
     * 
     * @author Frank
     * @date 2016年3月4日
     */
    private static final long serialVersionUID = 1L;


    /**
     * 角色名称
     */
    private String roleName;

    /**
     * 角色所拥有的权限
     */
    private List<PermissionEntity> perimissions;


    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public List<PermissionEntity> getPerimissions() {
        return perimissions;
    }

    public void setPerimissions(List<PermissionEntity> perimissions) {
        this.perimissions = perimissions;
    }


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.id
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.name
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.description
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.creat_user
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    private String creatUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.creat_time
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.modify_user
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.modify_time
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.id
     *
     * @return the value of role_info.id
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.id
     *
     * @param id the value for role_info.id
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.name
     *
     * @return the value of role_info.name
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.name
     *
     * @param name the value for role_info.name
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.description
     *
     * @return the value of role_info.description
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.description
     *
     * @param description the value for role_info.description
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.creat_user
     *
     * @return the value of role_info.creat_user
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    public String getCreatUser() {
        return creatUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.creat_user
     *
     * @param creatUser the value for role_info.creat_user
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    public void setCreatUser(String creatUser) {
        this.creatUser = creatUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.creat_time
     *
     * @return the value of role_info.creat_time
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.creat_time
     *
     * @param creatTime the value for role_info.creat_time
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.modify_user
     *
     * @return the value of role_info.modify_user
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.modify_user
     *
     * @param modifyUser the value for role_info.modify_user
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.modify_time
     *
     * @return the value of role_info.modify_time
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.modify_time
     *
     * @param modifyTime the value for role_info.modify_time
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

}
