/**
 * @项目名称: ruma-web
 * @文件名称: UserRoleEntity.java
 * @Date: 2016年3月8日
 * @Copyright: 2016-2016 www.neunn.com All rights reserved. 注意：本内容仅限于东网科技有限公司内部传阅，禁止外泄以及用于其他的商业目的
 */
package com.neunn.ruma.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * FIXME 此处填写类的描述信息
 * 
 * @author Frank
 * @date 2016年3月8日
 * @since 1.0
 */
public class UserRoleEntity implements Serializable {
    /** 
     * FIXME 删除本行替换为字段描述 
     * @author Frank
     * @date 2016年3月11日 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * user_role_info.id
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * user_role_info.user_id
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * user_role_info.role_id
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * user_role_info.creat_user
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    private String creatUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * user_role_info.creat_time
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * user_role_info.modify_user
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * user_role_info.modify_time
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    private Date modifyTime;

    private String roleName;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column user_role_info.id
     *
     * @return the value of user_role_info.id
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column user_role_info.id
     *
     * @param id the value for user_role_info.id
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column user_role_info.user_id
     *
     * @return the value of user_role_info.user_id
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column user_role_info.user_id
     *
     * @param userId the value for user_role_info.user_id
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column user_role_info.role_id
     *
     * @return the value of user_role_info.role_id
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column user_role_info.role_id
     *
     * @param roleId the value for user_role_info.role_id
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column user_role_info.creat_user
     *
     * @return the value of user_role_info.creat_user
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    public String getCreatUser() {
        return creatUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column user_role_info.creat_user
     *
     * @param creatUser the value for user_role_info.creat_user
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    public void setCreatUser(String creatUser) {
        this.creatUser = creatUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column user_role_info.creat_time
     *
     * @return the value of user_role_info.creat_time
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column user_role_info.creat_time
     *
     * @param creatTime the value for user_role_info.creat_time
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column user_role_info.modify_user
     *
     * @return the value of user_role_info.modify_user
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column user_role_info.modify_user
     *
     * @param modifyUser the value for user_role_info.modify_user
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column user_role_info.modify_time
     *
     * @return the value of user_role_info.modify_time
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column user_role_info.modify_time
     *
     * @param modifyTime the value for user_role_info.modify_time
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

}
