package com.neunn.ruma.dao;

import java.util.List;
import java.util.Map;

import com.neunn.ruma.common.bean.Page;
import com.neunn.ruma.common.persistence.annotation.MybatisDao;
import com.neunn.ruma.entity.ModuleEntity;

@MybatisDao
public interface ModuleDao {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * module_info
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * module_info
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    int insert(ModuleEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * module_info
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    int insertSelective(ModuleEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * module_info
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    ModuleEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * module_info
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    int updateByPrimaryKeySelective(ModuleEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * module_info
     *
     * @mbggenerated Wed May 27 11:13:48 CST 2015
     */
    int updateByPrimaryKey(ModuleEntity record);

    List<ModuleEntity> selectByCondition(Page<?> condition);

    List<ModuleEntity> selectByParentId(Map<String, Object> map);

    List<ModuleEntity> selectRightsTreeByModuleId(String roleId);

    List<ModuleEntity> selectByRoleId(String roleId);

    ModuleEntity queryChildrenByPrimaryKey(String id, String parentId);
}
