/**
 * @项目名称: ruma-web
 * @文件名称: MenuHandler.java
 * @Date: 2016年2月17日
 * @Copyright: 2016-2016 www.neunn.com All rights reserved. 注意：本内容仅限于东网科技有限公司内部传阅，禁止外泄以及用于其他的商业目的
 */
package com.neunn.ruma.dao;

import java.util.List;

import com.neunn.ruma.common.bean.Page;
import com.neunn.ruma.common.persistence.annotation.MybatisDao;
import com.neunn.ruma.entity.RoleEntity;

/**
 * 角色管理的数据库访问接口申请
 * 
 * @author Frank
 * @date 2016年2月17日
 * @since 1.0
 */
@MybatisDao
public interface RoleDao {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * role_info
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * role_info
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    int insert(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * role_info
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    int insertSelective(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * role_info
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    RoleEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * role_info
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    int updateByPrimaryKeySelective(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * role_info
     *
     * @mbggenerated Wed May 27 11:11:09 CST 2015
     */
    int updateByPrimaryKey(RoleEntity record);

    List<RoleEntity> selectByCondition(Page<?> condition);

    List<RoleEntity> selectByUserId(String userId);

    List<RoleEntity> getRoleByName(String roleName);
}
