/**
 * @项目名称: ruma-web
 * @文件名称: UserRoleDao.java
 * @Date: 2016年3月8日
 * @Copyright: 2016-2016 www.neunn.com All rights reserved. 注意：本内容仅限于东网科技有限公司内部传阅，禁止外泄以及用于其他的商业目的
 */
package com.neunn.ruma.dao;

import java.util.List;

import com.neunn.ruma.common.persistence.CrudDao;
import com.neunn.ruma.common.persistence.annotation.MybatisDao;
import com.neunn.ruma.entity.UserRoleEntity;

/**
 * 用户角色关系dao
 * 
 * @author Frank
 * @date 2016年3月8日
 * @since 1.0
 */
@MybatisDao
public interface UserRoleDao extends CrudDao<UserRoleEntity> {


    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_role_info
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_role_info
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    int insert(UserRoleEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_role_info
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    int insertSelective(UserRoleEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_role_info
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    UserRoleEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_role_info
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    int updateByPrimaryKeySelective(UserRoleEntity record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * user_role_info
     *
     * @mbggenerated Wed May 27 10:45:52 CST 2015
     */
    int updateByPrimaryKey(UserRoleEntity record);

    List<UserRoleEntity> selectByUserId(String userId);

    List<UserRoleEntity> selectByRoleId(String roleId);

    int delete(UserRoleEntity record);


}
